from enum import Enum


class DealType(str, Enum):
    DIRECT_LOAN = "DIRECT_LOAN"
    FUND_INVESTMENT = "FUND_INVESTMENT"
    EQUITY_STAKE = "EQUITY_STAKE"
    SPV_NOTE = "SPV_NOTE"


class DealStage(str, Enum):
    INTAKE = "INTAKE"
    QUALIFIED = "QUALIFIED"
    IC_REVIEW = "IC_REVIEW"
    CONDITIONAL = "CONDITIONAL"
    APPROVED = "APPROVED"
    CONVERTED_TO_ASSET = "CONVERTED_TO_ASSET"
    REJECTED = "REJECTED"
    CLOSED = "CLOSED"


class RejectionCode(str, Enum):
    OUT_OF_MANDATE = "OUT_OF_MANDATE"
    TICKET_TOO_SMALL = "TICKET_TOO_SMALL"
    JURISDICTION_EXCLUDED = "JURISDICTION_EXCLUDED"
    INSUFFICIENT_RETURN = "INSUFFICIENT_RETURN"
    WEAK_CREDIT_PROFILE = "WEAK_CREDIT_PROFILE"
    NO_COLLATERAL = "NO_COLLATERAL"

