"""Rebalance workflow service.

Implements the rebalance cascade state machine:
    ok → warning → breach → hard_stop

Each state transition creates a RebalanceEvent with actor_source tracking.

Config is injected as parameter by callers via ConfigService.
"""

import uuid
from dataclasses import dataclass
from datetime import date
from decimal import Decimal
from typing import Any

import structlog
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.domains.wealth.models.portfolio import PortfolioSnapshot
from app.domains.wealth.models.rebalance import RebalanceEvent
from quant_engine.cvar_service import resolve_cvar_config

logger = structlog.get_logger()

# Valid status transitions
VALID_TRANSITIONS = {
    "pending": {"approved", "rejected", "cancelled"},
    "approved": {"executed"},
    "rejected": set(),
    "cancelled": set(),
    "executed": set(),
}


@dataclass
class CascadeResult:
    previous_status: str
    new_status: str
    event_created: bool
    event_id: uuid.UUID | None = None
    reason: str | None = None


def determine_cascade_action(
    trigger_status: str,
    previous_trigger_status: str | None,
    cvar_utilized_pct: float,
    consecutive_breach_days: int,
    profile: str,
    config: dict | None = None,
) -> tuple[str | None, str | None]:
    """Determine if a cascade action is needed based on status transition.

    Args:
        config: portfolio_profiles config dict from ConfigService.

    Returns (event_type, trigger_reason) or (None, None) if no action needed.
    """
    profiles = resolve_cvar_config(config)
    profile_config = profiles[profile]

    if trigger_status == "ok":
        return None, None

    if trigger_status == "warning" and previous_trigger_status in (None, "ok"):
        return "cvar_breach", (
            f"CVaR utilization at {cvar_utilized_pct:.1f}% "
            f"(warning threshold: {profile_config['warning_pct'] * 100:.0f}%)"
        )

    if trigger_status == "breach" and previous_trigger_status != "breach":
        return "cvar_breach", (
            f"CVaR breach: {consecutive_breach_days} consecutive days "
            f"above limit (threshold: {profile_config['breach_days']})"
        )

    return None, None


async def create_system_rebalance_event(
    db: AsyncSession,
    profile: str,
    event_type: str,
    trigger_reason: str,
    weights_before: dict[str, Any] | None = None,
    cvar_before: float | None = None,
    actor_source: str = "system",
) -> RebalanceEvent:
    """Create a rebalance event generated by the system (not manual)."""
    event = RebalanceEvent(
        profile=profile,
        event_date=date.today(),
        event_type=event_type,
        trigger_reason=trigger_reason,
        weights_before=weights_before,
        cvar_before=Decimal(str(round(cvar_before, 6))) if cvar_before is not None else None,
        status="pending",
        actor_source=actor_source,
    )
    db.add(event)
    await db.flush()
    await db.refresh(event)
    logger.info(
        "System rebalance event created",
        event_id=str(event.event_id),
        profile=profile,
        event_type=event_type,
        actor_source=actor_source,
    )
    return event


async def process_cascade(
    db: AsyncSession,
    profile: str,
    trigger_status: str,
    cvar_utilized_pct: float,
    consecutive_breach_days: int,
    cvar_current: float | None = None,
    current_weights: dict[str, Any] | None = None,
    config: dict | None = None,
) -> CascadeResult:
    """Process the rebalance cascade for a profile.

    Args:
        config: portfolio_profiles config dict from ConfigService.
    """
    stmt = (
        select(PortfolioSnapshot.trigger_status)
        .where(PortfolioSnapshot.profile == profile)
        .order_by(PortfolioSnapshot.snapshot_date.desc())
        .limit(1)
    )
    result = await db.execute(stmt)
    previous_status = result.scalar_one_or_none()

    event_type, reason = determine_cascade_action(
        trigger_status,
        previous_status,
        cvar_utilized_pct,
        consecutive_breach_days,
        profile,
        config=config,
    )

    if event_type is None:
        return CascadeResult(
            previous_status=previous_status or "ok",
            new_status=trigger_status,
            event_created=False,
        )

    event = await create_system_rebalance_event(
        db,
        profile=profile,
        event_type=event_type,
        trigger_reason=reason,
        weights_before=current_weights,
        cvar_before=cvar_current,
        actor_source="system",
    )

    return CascadeResult(
        previous_status=previous_status or "ok",
        new_status=trigger_status,
        event_created=True,
        event_id=event.event_id,
        reason=reason,
    )


def validate_status_transition(current_status: str, new_status: str) -> bool:
    """Check if a status transition is valid."""
    valid_next = VALID_TRANSITIONS.get(current_status, set())
    return new_status in valid_next
