// ============================================================
// DAX — Medidas SEC (Manager Intelligence)
// Copie cada medida em: Home → New Measure
// ============================================================

// ── AUM ──────────────────────────────────────────────────────

Total AUM ($B) =
DIVIDE(SUM(SEC_Managers[aum_total]), 1000000000)

AUM Discretionary ($B) =
DIVIDE(SUM(SEC_Managers[aum_discretionary]), 1000000000)

AUM Share Discretionary % =
DIVIDE(
    SUM(SEC_Managers[aum_discretionary]),
    SUM(SEC_Managers[aum_total]),
    0
) * 100

// ── Holdings ─────────────────────────────────────────────────

Total Portfolio Value ($M) =
DIVIDE(SUM(SEC_Holdings[market_value]), 1000000)

Position Count =
COUNTROWS(SEC_Holdings)

Unique Issuers =
DISTINCTCOUNT(SEC_Holdings[cusip])

// HHI — Índice de concentração do portfólio (0=diversificado, 1=concentrado)
Portfolio HHI =
VAR TotalVal = SUM(SEC_Holdings[market_value])
VAR Weights =
    ADDCOLUMNS(
        VALUES(SEC_Holdings[cusip]),
        "w", DIVIDE(
            CALCULATE(SUM(SEC_Holdings[market_value])),
            TotalVal,
            0
        )
    )
RETURN
    SUMX(Weights, [w] ^ 2)

Top 10 Holdings Value ($M) =
CALCULATE(
    DIVIDE(SUM(SEC_Holdings[market_value]), 1000000),
    TOPN(10, SEC_Holdings, SEC_Holdings[market_value], DESC)
)

Top 10 Concentration % =
DIVIDE(
    [Top 10 Holdings Value ($M)],
    [Total Portfolio Value ($M)],
    0
) * 100
