// ============================================================
// DAX — Medidas ESMA (Universo UCITS)
// ============================================================

// ── Universo de fundos ────────────────────────────────────────

Total UCITS Funds =
COUNTROWS(ESMA_Funds)

Tradeable UCITS Funds =
CALCULATE(
    COUNTROWS(ESMA_Funds),
    ESMA_Tickers[is_tradeable] = TRUE()
)

Tradeable Coverage % =
DIVIDE([Tradeable UCITS Funds], [Total UCITS Funds], 0) * 100

// ── Distribuição geográfica ───────────────────────────────────

Funds by Domicile =
COUNTROWS(ESMA_Funds)
// (usar com slicer/filtro na coluna domicile)

Unique Managers =
DISTINCTCOUNT(ESMA_Funds[esma_manager_id])

Avg Funds per Manager =
DIVIDE([Total UCITS Funds], [Unique Managers], 0)

// ── NAV Analysis ─────────────────────────────────────────────

Latest NAV Date =
MAX(ESMA_NAV[nav_date])

Latest NAV Value =
CALCULATE(
    LASTNONBLANK(ESMA_NAV[nav_value], 1),
    ESMA_NAV[nav_date] = [Latest NAV Date]
)

NAV 1Y Return % =
VAR LatestDate = MAX(ESMA_NAV[nav_date])
VAR LatestVal  = CALCULATE(
    MAX(ESMA_NAV[nav_value]),
    ESMA_NAV[nav_date] = LatestDate
)
VAR DateOneYearAgo = LatestDate - 365
VAR ValOneYearAgo =
    CALCULATE(
        MAX(ESMA_NAV[nav_value]),
        ESMA_NAV[nav_date] = CALCULATE(
            MAX(ESMA_NAV[nav_date]),
            ESMA_NAV[nav_date] <= DateOneYearAgo
        )
    )
RETURN
    DIVIDE(LatestVal - ValOneYearAgo, ValOneYearAgo, BLANK()) * 100

NAV 3M Return % =
VAR LatestDate = MAX(ESMA_NAV[nav_date])
VAR LatestVal  = CALCULATE(MAX(ESMA_NAV[nav_value]), ESMA_NAV[nav_date] = LatestDate)
VAR Date3MAgo  = LatestDate - 90
VAR Val3MAgo   =
    CALCULATE(
        MAX(ESMA_NAV[nav_value]),
        ESMA_NAV[nav_date] = CALCULATE(
            MAX(ESMA_NAV[nav_date]),
            ESMA_NAV[nav_date] <= Date3MAgo
        )
    )
RETURN
    DIVIDE(LatestVal - Val3MAgo, Val3MAgo, BLANK()) * 100
