// ============================================================
// DAX — Medidas Macro (IMF + BIS + FRED + Treasury)
// ============================================================

// ── IMF WEO ───────────────────────────────────────────────────

GDP Growth Forecast % =
CALCULATE(
    AVERAGE(IMF_Forecasts[value]),
    IMF_Forecasts[indicator] = "NGDP_RPCH"
)

Inflation Forecast % =
CALCULATE(
    AVERAGE(IMF_Forecasts[value]),
    IMF_Forecasts[indicator] = "PCPIPCH"
)

Fiscal Balance % GDP =
CALCULATE(
    AVERAGE(IMF_Forecasts[value]),
    IMF_Forecasts[indicator] = "GGXCNL_NGDP"
)

Govt Debt % GDP =
CALCULATE(
    AVERAGE(IMF_Forecasts[value]),
    IMF_Forecasts[indicator] = "GGXWDG_NGDP"
)

// ── BIS Statistics ────────────────────────────────────────────

Credit to GDP Gap =
CALCULATE(
    AVERAGE(BIS_Statistics[value]),
    BIS_Statistics[indicator] = "credit_to_gdp_gap"
)

Debt Service Ratio =
CALCULATE(
    AVERAGE(BIS_Statistics[value]),
    BIS_Statistics[indicator] = "debt_service_ratio"
)

Property Price Index =
CALCULATE(
    AVERAGE(BIS_Statistics[value]),
    BIS_Statistics[indicator] = "property_prices"
)

// ── Benchmark Performance ─────────────────────────────────────

Benchmark Latest Close =
CALCULATE(
    MAX(Benchmark_NAV[close]),
    Benchmark_NAV[time] = MAX(Benchmark_NAV[time])
)

Benchmark YTD Return % =
VAR LatestDate = MAX(Benchmark_NAV[time])
VAR LatestClose = CALCULATE(MAX(Benchmark_NAV[close]), Benchmark_NAV[time] = LatestDate)
VAR YearStart = DATE(YEAR(LatestDate), 1, 1)
VAR YearStartClose =
    CALCULATE(
        MAX(Benchmark_NAV[close]),
        Benchmark_NAV[time] = CALCULATE(
            MAX(Benchmark_NAV[time]),
            Benchmark_NAV[time] >= YearStart,
            Benchmark_NAV[time] <= YearStart + 5
        )
    )
RETURN
    DIVIDE(LatestClose - YearStartClose, YearStartClose, BLANK()) * 100
