"""Frozen dataclasses for long-form report generation."""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import date
from typing import Any


@dataclass(frozen=True, slots=True)
class AllocationItem:
    """Allocation row for Long-Form DD Report PDF."""

    block_id: str
    block_name: str
    portfolio_weight: float
    benchmark_weight: float
    active_weight: float


@dataclass(frozen=True, slots=True)
class AttributionItem:
    """Attribution row for Long-Form DD Report PDF."""

    block_name: str
    allocation_effect: float
    selection_effect: float
    total_effect: float


@dataclass(frozen=True, slots=True)
class LongFormReportData:
    """All data needed to render the Long-Form DD Report PDF.

    Built by LongFormPDFRenderer from LongFormReportResult + supplementary
    DB queries. Frozen — safe across async boundaries.
    """

    portfolio_id: str
    portfolio_name: str
    profile: str
    as_of: date
    regime: str  # "expansion" | "contraction" | "crisis" | "risk_off"

    # Performance summary
    active_return_bps: float | None = None
    cvar_95: float | None = None
    avg_expense_ratio: float | None = None
    instrument_count: int = 0

    # Allocation
    allocations: list[AllocationItem] = field(default_factory=list)

    # Attribution
    attribution: list[AttributionItem] = field(default_factory=list)

    # Chapters (already generated by LongFormReportEngine)
    chapters: list[ChapterResult] = field(default_factory=list)

    # Risk
    volatility: float | None = None
    sharpe: float | None = None
    max_drawdown: float | None = None

    # Stress scenarios
    stress: list[dict[str, Any]] = field(default_factory=list)

    # Holdings
    holdings: list[dict[str, Any]] = field(default_factory=list)


@dataclass(frozen=True, slots=True)
class ChapterResult:
    """Result of a single chapter generation."""

    tag: str
    order: int
    title: str
    content: dict[str, Any] = field(default_factory=dict)
    status: str = "completed"  # "completed" | "failed"
    confidence: float = 1.0
    error: str | None = None


@dataclass(frozen=True, slots=True)
class LongFormReportResult:
    """Complete long-form report result."""

    portfolio_id: str
    chapters: list[ChapterResult] = field(default_factory=list)
    status: str = "completed"  # "completed" | "partial" | "failed"
    error: str | None = None


CHAPTER_REGISTRY: list[dict[str, Any]] = [
    {"tag": "macro_context", "order": 1, "title": "Macro Context"},
    {"tag": "strategic_allocation", "order": 2, "title": "Strategic Allocation Rationale"},
    {"tag": "portfolio_composition", "order": 3, "title": "Portfolio Composition & Changes"},
    {"tag": "performance_attribution", "order": 4, "title": "Performance Attribution"},
    {"tag": "risk_decomposition", "order": 5, "title": "Risk Decomposition"},
    {"tag": "fee_analysis", "order": 6, "title": "Fee Analysis"},
    {"tag": "per_fund_highlights", "order": 7, "title": "Per-Fund Highlights"},
    {"tag": "forward_outlook", "order": 8, "title": "Forward Outlook"},
]
