from __future__ import annotations

import io
import uuid
from datetime import UTC, datetime
from typing import Any

from fastapi import APIRouter, Depends
from fastapi.responses import StreamingResponse
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.core.security.clerk_auth import Actor, get_actor, require_fund_access, require_role
from app.core.tenancy.middleware import get_db_with_rls
from app.domains.credit.modules.ai.models import AIAnswer, AIAnswerCitation, AIQuestion

router = APIRouter(tags=["Evidence Pack"], dependencies=[Depends(require_fund_access())])


async def _build_evidence_manifest(db: AsyncSession, fund_id: uuid.UUID, limit: int, actor: Actor) -> dict[str, Any]:
    result = await db.execute(
        select(AIAnswer).where(AIAnswer.fund_id == fund_id).order_by(AIAnswer.created_at_utc.desc()).limit(limit),
    )
    answers = list(result.scalars().all())
    answer_ids = [a.id for a in answers]

    q_result = await db.execute(
        select(AIQuestion).where(AIQuestion.fund_id == fund_id, AIQuestion.id.in_([a.question_id for a in answers])),
    )
    questions = list(q_result.scalars().all())
    by_q = {q.id: q for q in questions}

    citations: list[AIAnswerCitation] = []
    if answer_ids:
        c_result = await db.execute(
            select(AIAnswerCitation).where(AIAnswerCitation.fund_id == fund_id, AIAnswerCitation.answer_id.in_(answer_ids)),
        )
        citations = list(c_result.scalars().all())
    by_answer: dict[uuid.UUID, list[AIAnswerCitation]] = {}
    for c in citations:
        by_answer.setdefault(c.answer_id, []).append(c)

    manifest: dict[str, Any] = {
        "fund_id": str(fund_id),
        "generated_by": actor.actor_id,
        "items": [],
    }
    for a in answers:
        q = by_q.get(a.question_id)
        item = {
            "question_id": str(a.question_id),
            "answer_id": str(a.id),
            "question": q.question_text if q else None,
            "answer": a.answer_text,
            "created_at_utc": a.created_at_utc.isoformat() if a.created_at_utc else None,
            "citations": [
                {
                    "chunk_id": str(c.chunk_id),
                    "document_id": str(c.document_id),
                    "version_id": str(c.version_id),
                    "page_start": c.page_start,
                    "page_end": c.page_end,
                    "excerpt": c.excerpt,
                    "source_blob": c.source_blob,
                }
                for c in by_answer.get(a.id, [])
            ],
        }
        manifest["items"].append(item)
    return manifest


@router.post("/funds/{fund_id}/reports/evidence-pack")
async def export_evidence_pack(
    fund_id: uuid.UUID,
    payload: dict | None = None,
    db: AsyncSession = Depends(get_db_with_rls),
    actor: Actor = Depends(get_actor),
    _role_guard: Actor = Depends(require_role(["ADMIN", "GP", "COMPLIANCE", "AUDITOR"])),
) -> dict[str, Any]:
    """v1 output: JSON manifest (future EPIC: PDF binder)."""
    payload = payload or {}
    limit = max(1, min(200, int(payload.get("limit", 20))))
    return await _build_evidence_manifest(db, fund_id, limit, actor)


def _build_evidence_pdf(manifest: dict) -> bytes:
    """Generate a PDF binder from the evidence pack manifest."""
    from reportlab.lib.pagesizes import A4
    from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
    from reportlab.lib.units import mm
    from reportlab.platypus import HRFlowable, Paragraph, SimpleDocTemplate, Spacer

    buf = io.BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=A4, topMargin=20 * mm, bottomMargin=20 * mm)
    styles = getSampleStyleSheet()

    title_style = ParagraphStyle("EvidenceTitle", parent=styles["Heading1"], fontSize=16, spaceAfter=6 * mm)
    h2_style = ParagraphStyle("EvidenceH2", parent=styles["Heading2"], fontSize=12, spaceAfter=4 * mm)
    body_style = styles["BodyText"]
    cite_style = ParagraphStyle("Citation", parent=styles["BodyText"], fontSize=8, leftIndent=10 * mm, textColor="grey")

    elements = []

    elements.append(Paragraph("Evidence Pack -- Audit Binder", title_style))
    elements.append(Paragraph(
        f"Fund: {manifest.get('fund_id', 'N/A')}<br/>"
        f"Generated by: {manifest.get('generated_by', 'N/A')}<br/>"
        f"Date: {datetime.now(UTC).strftime('%Y-%m-%d %H:%M UTC')}<br/>"
        f"Items: {len(manifest.get('items', []))}",
        body_style,
    ))
    elements.append(Spacer(1, 8 * mm))
    elements.append(HRFlowable(width="100%", thickness=1))
    elements.append(Spacer(1, 4 * mm))

    for idx, item in enumerate(manifest.get("items", []), 1):
        question = item.get("question") or "(no question)"
        answer = item.get("answer") or "(no answer)"
        created = item.get("created_at_utc") or ""

        elements.append(Paragraph(f"Item {idx}: {question[:200]}", h2_style))
        elements.append(Paragraph(f"<i>Created: {created}</i>", cite_style))
        elements.append(Spacer(1, 2 * mm))

        safe_answer = answer.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
        for para in safe_answer.split("\n\n"):
            if para.strip():
                elements.append(Paragraph(para.strip(), body_style))
                elements.append(Spacer(1, 2 * mm))

        citations = item.get("citations", [])
        if citations:
            elements.append(Spacer(1, 2 * mm))
            elements.append(Paragraph(f"<b>Citations ({len(citations)})</b>", body_style))
            for c in citations:
                source = c.get("source_blob") or "unknown"
                pages = ""
                if c.get("page_start"):
                    pages = f" (pp. {c['page_start']}"
                    if c.get("page_end") and c["page_end"] != c["page_start"]:
                        pages += f"-{c['page_end']}"
                    pages += ")"
                excerpt = (c.get("excerpt") or "")[:300]
                safe_excerpt = excerpt.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
                elements.append(Paragraph(
                    f"[{source}{pages}] {safe_excerpt}",
                    cite_style,
                ))

        elements.append(HRFlowable(width="100%", thickness=0.5))
        elements.append(Spacer(1, 4 * mm))

    elements.append(Spacer(1, 10 * mm))
    elements.append(Paragraph(
        "<i>This document was generated by the Netz Private Credit OS evidence pack system. "
        "All citations reference indexed document chunks with provenance tracking.</i>",
        cite_style,
    ))

    doc.build(elements)
    buf.seek(0)
    return buf.read()


@router.post("/funds/{fund_id}/reports/evidence-pack/pdf")
async def export_evidence_pack_pdf(
    fund_id: uuid.UUID,
    payload: dict | None = None,
    db: AsyncSession = Depends(get_db_with_rls),
    actor: Actor = Depends(get_actor),
    _role_guard: Actor = Depends(require_role(["ADMIN", "GP", "COMPLIANCE", "AUDITOR"])),
):
    """Generate a PDF binder of the evidence pack for audit purposes."""
    import asyncio

    payload = payload or {}
    limit = max(1, min(200, int(payload.get("limit", 50))))
    manifest = await _build_evidence_manifest(db, fund_id, limit, actor)

    loop = asyncio.get_event_loop()
    pdf_bytes = await loop.run_in_executor(None, _build_evidence_pdf, manifest)

    return StreamingResponse(
        io.BytesIO(pdf_bytes),
        media_type="application/pdf",
        headers={
            "Content-Disposition": f'attachment; filename="evidence_pack_{fund_id}.pdf"',
        },
    )
